# Generated by Django 5.2.5 on 2025-08-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='departement',
            new_name='department',
        ),
    ]
